### ISSUE TITLE
actor fail with error of incorrect use of Node.js. it is not usable.

### ISSUE THREAD

**Issue by tomerbm** [gustavotr/actor-macys-scraper#13]
see part of the log. it failed after 180 items.
so it is not usable. can you please assist?

021-10-08T08:10:28.379Z INFO  Statistics: BasicCrawler request statistics: {"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":1437,"requestsFinishedPerMinute":145,"requestsFailedPerMinute":0,"requestTotalDurationMillis":208361,"requestsTotal":145,"crawlerRuntimeMillis":60137,"retryHistogram":[145]}
2021-10-08T08:10:28.430Z INFO  BasicCrawler:AutoscaledPool: state {"currentConcurrency":7,"desiredConcurrency":8,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":0.214},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.091},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2021-10-08T08:10:28.729Z INFO  Processing https://www.macys.com/shop/product/msk-beaded-strap-capelet-back-dress?ID=12650841&CategoryID=5449...
2021-10-08T08:10:28.747Z INFO  Processing https://www.macys.com/shop/product/sl-fashions-plus-size-sequined-ruffled-halter-gown?ID=12672229&CategoryID=5449...
2021-10-08T08:10:28.920Z INFO  Processing https://www.macys.com/shop/product/anne-klein-mesh-fit-flare-dress?ID=12905831&CategoryID=5449...
2021-10-08T08:10:29.008Z INFO  Processing https://www.macys.com/shop/product/alex-evenings-petite-soutache-a-line-party-dress?ID=12995069&CategoryID=5449...
2021-10-08T08:10:29.037Z INFO  Processing https://www.macys.com/shop/product/sl-fashions-plus-size-lace-capelet-gown?ID=13185992&CategoryID=5449...
2021-10-08T08:10:29.441Z INFO  Processing https://www.macys.com/shop/product/js-collections-embellished-lace-sheath-dress?ID=12665466&CategoryID=5449...
2021-10-08T08:10:29.821Z INFO  Processing https://www.macys.com/shop/product/b-darlin-juniors-velvet-off-the-shoulder-fit-flare-dress?ID=12725614&CategoryID=5449...
2021-10-08T08:10:29.866Z INFO  Processing https://www.macys.com/shop/product/alex-evenings-petite-sequin-lace-gown?ID=13186029&CategoryID=5449...
2021-10-08T08:10:30.520Z INFO  Processing https://www.macys.com/shop/product/r-m-richards-embellished-cape-dress?ID=13065944&CategoryID=5449...
2021-10-08T08:10:30.600Z INFO  Processing https://www.macys.com/shop/product/city-studios-juniors-high-neck-fit-flare-dress?ID=12696072&CategoryID=5449...
2021-10-08T08:10:31.092Z node:internal/process/promises:245
2021-10-08T08:10:31.093Z           triggerUncaughtException(err, true /* fromPromise */);
2021-10-08T08:10:31.093Z           ^
2021-10-08T08:10:31.094Z 
2**021-10-08T08:10:31.094Z **Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.****
2021-10-08T08:10:31.095Z Please open an issue with this stack trace at https://github.com/nodejs/node/issues
2021-10-08T08:10:31.095Z 
2021-10-08T08:10:31.096Z     at new NodeError (node:internal/errors:329:5)
2021-10-08T08:10:31.096Z     at assert (node:internal/assert:14:11)
2021-10-08T08:10:31.096Z     at ClientRequest.Writable.destroy (node:internal/streams/writable:851:5)
2021-10-08T08:10:31.097Z     at Request._destroy (/usr/src/app/node_modules/got/dist/source/core/index.js:1368:32)
2021-10-08T08:10:31.097Z     at _destroy (node:internal/streams/destroy:67:23)
2021-10-08T08:10:31.098Z     at Request.destroy (node:internal/streams/destroy:59:5)
2021-10-08T08:10:31.098Z     at Request._error (/usr/src/app/node_modules/got/dist/source/core/index.js:1190:14)
2021-10-08T08:10:31.099Z     at /usr/src/app/node_modules/got/dist/source/core/index.js:1270:23
2021-10-08T08:10:31.099Z     at runMicrotasks (<anonymous>)
2021-10-08T08:10:31.100Z     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
2021-10-08T08:10:31.100Z   code: 'ERR_INTERNAL_ASSERTION'
2021-10-08T08:10:31.101Z }
2021-10-08T08:10:31.105Z npm notice 
2021-10-08T08:10:31.106Z npm notice New major version of npm available! 7.7.6 -> 8.0.0
2021-10-08T08:10:31.106Z npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.0.0
2021-10-08T08:10:31.107Z npm notice Run npm install -g npm@8.0.0 to update!
2021-10-08T08:10:31.107Z npm notice 
2021-10-08T08:10:31.218Z

**Comment by gustavotr** [comment]
Ok @tomerbm, seems to be fixed now. Can you test it?

**Comment by tomerbm** [comment]
Thx, already developed my own.
